eureka:
  client:
    service-url:
      defaultZone: http://${eureka:localhost}:8761/eureka


spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://${zipkin:localhost}:9411/
    sender:
      type: rabbit
  rabbitmq:
    host: localhost