server:
  port: 5002

spring:
  mvc:
    converters:
      preferred-json-mapper:gson
    pathmatch:
      matching-strategy: ant-path-matcher
  config:
    activate:
      on-profile: default
  application:
    name: catalogue
  data:
    mongodb:
      user: root
      password: rootpassword
      uri: mongodb://${catalogue-db:localhost}:${catalogue-db-port:27017}/catalogue-db
  jpa:
    hibernate:
      ddl-auto: update