server:
  port: 8083

spring:
  mvc:
    converters:
      preferred-json-mapper:gson
    pathmatch:
      matching-strategy: ant-path-matcher
  config:
    activate:
      on-profile: default
  application:
    name: holiday-reservation-flight
  datasource:
    url: jdbc:mysql://${holiday-reservation-flight-db:localhost}:${holiday-reservation-flight-db-port:3308}/holiday-reservation-flight-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


--- # Testing configuration

server:
  port: ${random.int(5000,5100)}

spring:
  mvc:
    converters:
      preferred-json-mapper:gson
  config:
    activate:
      on-profile: test
  application:
    name: holiday-reservation-flight
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true